### ISSUE TITLE
Crash due to missing List::reversed method

### ISSUE THREAD

**Issue by FliegendeWurst** [FliegendeWurst/TriliumDroid#6]
As reported by @MatejPetrik007 in https://github.com/FliegendeWurst/TriliumDroid/issues/3#issuecomment-2526360459

```
java.lang.NoSuchMethodError: No interface method reversed()Ljava/util/List; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /apex/com.android.art/javalib/core-oj.jar)
       at eu.fliegendewurst.triliumdroid.MainActivity.navigateTo(MainActivity.kt:507)
       at eu.fliegendewurst.triliumdroid.MainActivity.navigateTo$default(MainActivity.kt:445)
       at eu.fliegendewurst.triliumdroid.MainActivity.showInitialNote(MainActivity.kt:262)
       at eu.fliegendewurst.triliumdroid.MainActivity.access$showInitialNote(MainActivity.kt:59)
       at eu.fliegendewurst.triliumdroid.MainActivity$startSync$1$3.invoke$lambda$1(MainActivity.kt:252)
       at eu.fliegendewurst.triliumdroid.MainActivity$startSync$1$3.$r8$lambda$OETiGqtLqASwWJpDHZ928dhcpd0(Unknown Source:0)
       at eu.fliegendewurst.triliumdroid.MainActivity$startSync$1$3$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7924)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by FliegendeWurst** [comment]
It appears the issue is due to using compile SDK 35: https://issuetracker.google.com/issues/350432371

Will be fixed in next release

**Comment by MatejPetrik007** [comment]
confirmed that it is fixed - its working on the One Plus 5
