### ISSUE TITLE
Investigate leak warning

### ISSUE THREAD

**Issue by FliegendeWurst** [FliegendeWurst/TriliumDroid#9]
Shortly after starting the app, the following is printed to the console:

```
StrictMode policy violation:
android.os.strictmode.LeakedClosableViolation:
A resource was acquired at attached stack trace but never released.
See java.io.Closeable for information on avoiding resource leaks.
Callsite: close
 at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1992)
 at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:338)
 at sun.nio.fs.UnixSecureDirectoryStream.finalize(UnixSecureDirectoryStream.java:580)
 at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:370)
 at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:350)
 at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:322)
 at java.lang.Daemons$Daemon.run(Daemons.java:131)
 at java.lang.Thread.run(Thread.java:1012)
```

Unfortunately I don't know where the app uses a `UnixSecureDirectoryStream` without closing it.

**Comment by FliegendeWurst** [comment]
Seems fixed by new build tools https://stackoverflow.com/questions/67444092/how-to-debug-leak-caused-by-unixdirectorystream-in-android-app
